### ISSUE TITLE
Inquiry Regarding DGLError During Pretraining in STANDS

### ISSUE THREAD

**Issue by Zhihong-Lin** [Catchxu/STANDS#5]
I am currently working with the STANDS tool for spatial transcriptomics analysis, and I encountered an issue during the pretraining process. Specifically, I received the following error:

```
DGLError: Caught DGLError in prefetcher.
```

I suspect this error might be related to how the image data is structured in `adata.uns['spatial']`. In particular, I have placed the image data under `adata.uns['spatial']` in my dataset, but I am unsure whether the structure is compatible with the expectations of the pretraining function.

To further troubleshoot this issue, could you kindly provide the sample data used in your tutorial? This would help me ensure that my data structure matches the one in the tutorial, allowing me to better understand and resolve the issue.

I would greatly appreciate any guidance or suggestions you may have regarding this problem.

Thank you for your time and assistance!

**Comment by Catchxu** [comment]
adata.uns['spatial'] may involve complex secondary and tertiary structures and need to be stored in the form of a dictionary, rather than just directly importing images in numpy.ndarray format. This operation is defined by anndata and scanpy (see https://scanpy.readthedocs.io/en/stable/api/generated/scanpy.pl.spatial.html#scanpy.pl.spatial), and if you need to use scanpy for visualization, you also need to store the image in this format.

Additionally, in issue  #4, I also responded to the data processing. And the updated preprocessed data can be downloaded at https://catchxu.github.io/STANDS/start/#datasets, the pretrained weights can be downloaded at https://catchxu.github.io/STANDS/start/#pretrained-weights.

**Comment by Zhihong-Lin** [comment]
Thank you very much for your detailed response . I will follow your suggestions and use the provided resources to proceed with my work.Thanks again for your support!
